### ISSUE TITLE
Cannot install with Forge support

### ISSUE THREAD

**Issue by cherbert** [jrbudda/minecrift#2]
I have Forge 10.13.4.1614 installed but when I use your installer the option to install with Forge is grayed out and cannot be selected.

**Comment by Teralink** [comment]
I have the same problem. Did a clean minecraft install and added forge 10.13.4.1614. The Minecrift installer 'minecrift-1.7.10-R2b-Vive-jrbudda3-installer.exe' doesn't allow me to tick the forge option.

**Comment by cherbert** [comment]
Just tried your version 4 forge blind install fix. It installs but when launching the profile you get an Unable to launch error.

This is the error when trying to launch the Vive Forge profile in the launcher...

http://pastebin.com/6jMabi4J

**Comment by Delectrixz** [comment]
Can confirm I'm getting the same error as Cherbert. Using forge 1614.

**Comment by jrbudda** [comment]
Ah ok, I removed that class because it had a dependency I couldn't find. I'll see if I can fix it, then we can get on to the real bugs.

**Comment by jrbudda** [comment]
Try dis, please.

[minecrift-1.7.10-R2b-Vive-jrbudda4-installer.zip](https://github.com/jrbudda/minecrift/files/280554/minecrift-1.7.10-R2b-Vive-jrbudda4-installer.zip)

**Comment by cherbert** [comment]
[22:37:42] [main/ERROR] [FML]: There is a binary discrepency between the expected input class bbj (bbj) and the actual class. Checksum on disk is 3e36d4e1, in patch 4dde7b8f. Things are probably about to go very wrong. Did you put something into the jar file?
[22:37:42] [main/ERROR] [FML]: The game is going to exit, because this is a critical error, and it is very improbable that the modded game will work, please obtain clean jar files.

**Comment by Delectrixz** [comment]
It works with minecraft+forge for me, just installed over the old version. Jumped in the game and it loaded up however FTB was spewing errors:

[http://pastebin.com/XNMhMXUN](http://pastebin.com/XNMhMXUN)

**Comment by Tyrindor** [comment]
Same here, works with minecraft+forge, but link an FTB modpack by changing the game directory and tons of errors. Doesn't happen on the non-modified vesrions of the vine mod. :(

Tried fresh installs too.

**Comment by cherbert** [comment]
okay, I deleted all the old profiles and bin files and re-installed fresh. It worked this time.

**Comment by Tyrindor** [comment]
I copied over all the "mods" from FTB to the .minecraft dictonary. It seems like it's not FTB causing it because this crashed too, some modification made (perhaps some forge code was edited in your tweaks?) is making a certain mod(s) not load correctly I think.

Overwriting with the default "minecrift-1.7.10-R2b-Vive-installer" fixes it.

**Comment by cherbert** [comment]
Most mods I have tried all fail though... Not sure if thats the Vive mod or the fact the mods I am trying don't like forge 1614?

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.<init>(Ljava/lang/String;)

**Comment by Tyrindor** [comment]
Same error. I'm using Infinity Evolved 2.5.0, tried fresh install but doesn't work with the modifications jrbudda made. It does work with the stock vive mod.

Something must have been edited that broke forge support. :(

**Comment by Delectrixz** [comment]
The FTB mod pack Mage Quest was working with the old "minecrift-1.7.10-R2b-Vive-installer", but it's not with this version of minecrift. Somethings causing a problem! Jrbudda to the rescue!

**Comment by jrbudda** [comment]
I got nothin. I have no experience at all with forge, much less trying to get forge to modify this much of base minecraft and then run mods on top of it. Seems like it does some kind of checksum checking on the base jar, and minecrift must be doing something to trick it, something likely needs to be changed in the build settings for each build.

If someone knows anything about how to go about fixing this I would appreciate it.

**Comment by Tyrindor** [comment]
All I can suggest is comparing code with the forge enabled vive mod version here that works: http://www.mediafire.com/download/9lz9dhwm2w5x832/minecrift-1.7.10-R2b-Vive-installer.exe

I don't think it's a checksumming error. cherbert fixed that issue by reinstalling it, probably an entirely different issue.

The actual errors:
http://pastebin.com/XNMhMXUN
http://pastebin.com/A5RVijZa

Sadly, vanilla Minecraft just doesn't hold my interest long so I'll be using the stock vive mod. Hopefully someone figures out the cause. My guess is something was changed that forge hooks into.

**Comment by ziggrrauglurr** [comment]
Since I can't test this (lack of Vive :/ ) I will only remind you that **most** mods are very finicky with their preferred forge version, something lower (or higher!), makes them go all bonkers.

**Comment by fucnknown** [comment]
Ok, since no one mentioned this, I 'm just going to remind everyone that mods are **_really**_ finicky if they don't get the forge version they want. 

Since I don't have a Vive, I'll try installing v4.5 and run it "normally", to try to narrow down the issue.

**Comment by Tyrindor** [comment]
I'm using Infinity Evolved which uses the same version of forge as Vine. Definitely not a forge version mismatch.

**Comment by cherbert** [comment]
> I 'm just going to remind everyone that mods are really finicky if they don't get the forge version they want.

The mod I am using works perfectly fine with Forge 1614

**Comment by Delectrixz** [comment]
Ive tried about 6 different forge versions and none seem to work prior to 1400, before even trying to install minecrift. 1614 seems to be the most stable. 

Old ftb/minecrift/mage quest setup that works also used 1614 which rules out any forge version differences as the culprit. Theres something different in the old minecrift that we need in the new one unfortunately im no coder.

**Comment by fucnknown** [comment]
Well on the plus side, Automat, was active on his fork 7 days ago, me might be able to summon him, he migh have insights on this, no?

**Comment by CaiganMythFang** [comment]
Greetings, I'm not a coder by any means, but a modpack dev that is used to deciphering some of the odd crashes, so hopefully I can help get things at least pointed in the right direction for a fix. =)

With the modpacks I've been able to get working on the original vivecraft port, I tested with v5 of your changes jrbudda. Pretty much all of them crash with a similar error, usually with different mods, the most common being :  

Caused by: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.<init>(Ljava/lang/String;)V

Searching some of the error lines, though, multiple places seem to be pointing out that this error is from part of Forge not being installed correctly. Specifically : Forge Mod Loader is installed, but not Forge Minecraft. Normally these get installed together via the normal installer.

It sounds like something is not building correctly with the new installer.

**Comment by jrbudda** [comment]
I think its installed, but has some kind of fit during startup and refuses to load the necessary files. Not really sure tho. I do know the vanilla creativetabs class does not have a (string) constructor so something is supposed to be modifying that file to add it.

**Comment by fucnknown** [comment]
Question. You forked Automat's version in tag R2b (The one that StellaArtois declared Forge 1614 working) ?  (I ask because of the name of your builds) Just to get my bearings were it diverged.
https://github.com/Automat-GH/minecrift/commit/c13ae3d335b84f0fe3dbf0410d2d371667aa34a7

**Comment by Delectrixz** [comment]
How about taking the original code from Automat-GH, then adding in a handful of the new additions / changes at a time, install it and see if it breaks. When it does bam you can narrow down the culprit!

**Comment by cherbert** [comment]
This is from the game output tab on the launcher. Something seems very wrong.

http://pastebin.com/pt1y8C31

Searching Google for similar errors seems to bring up discussions relating to gradlew not having been setup properly in your eclipse environment (assuming you are using eclipse?) and/or LWJGL being missing?

`gradlew setupDecompWorkspace eclipse`

**Comment by Tyrindor** [comment]
Zig, according to his file names he forked R2b. https://github.com/jrbudda/minecrift/releases

Our best bet is asking the original coder of the mod to look at it, but I don't see any way to message on github? Someone out there has to know the fix for this, the minecraft modding community is huge. I assume this guy would know, as he's the one who added forge support to the vive mod: https://github.com/StellaArtois

I also searched for the error "java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.(Ljava/lang/String;)V" and the only thing that really stuck out is the fact forge is very picky about how it's compiled.

http://www.minecraftforge.net/forum/index.php?topic=28206.0

**Comment by jrbudda** [comment]
Trying to set up to dig into this... can someone post me a console log of minecraft starting up where forge+mods load correctly with Automat's original? I tried it but get almost the exact same message spam as with my updated installs.

Thanks.

**Comment by CaiganMythFang** [comment]
Sure thing.

**MODPACK** : FTB Infinity Evolved Skyblock
**VERSION** : 1.1.0

I can't use pastebin for the logs due to their size, so this will be from my DropBox. These are the fml-client-latest.log files from minecraft/logs/, grabbed when the modpack either fully loads or when it crashes.

**AUTOMAT GH BUILD** : [Log File](https://www.dropbox.com/s/htodquy648h6706/Minecrift%20Vive%20-%20Automat%20GH%20build%20-%20FTB%20Infinity%20Skyblock%20%28working%29.log?dl=0)
This version works with no crashes.
**JRBUDDA V5 BUILD** : [Log File](https://www.dropbox.com/s/mbfi1ngt9kbw3au/Minecrift%20Vive%20-%20jrbudda%20v5%20build%20-%20FTB%20Infinity%20Skyblock%20%28crashing%29.log?dl=0)
This version crashes fairly quickly.

**Comment by jrbudda** [comment]
thank you, it does appear the have the same error spam, so that's not related. Good to know.

**Comment by jrbudda** [comment]
Ok so the gist of the issue is thus:

Both Forge and Minecrfit are fundamentally similar, they both add new code to the base game and both (heavily) modify the base game to support that new code. Both installers do approximately the same thing: they download the base game, deobfuscate it, add the new code, apply patches to the existing base game code, and reobfuscate it.

So the trick for compatibility is both sets of base game patches have to not step on each other's toes. I know for a fact I've modified some parts of base minecraft that Forge is not expecting so that creates a crash, fine, I think I can fix those. 

What I don't understand is this common error of NoSuchMethod related to CreativeTabs. CreativeTabs.java is code that only forge modifies in the base game, but Minecrift does not touch.

My only guess is it's an obfuscation error, something in the Minecrift build process is creating an obfuscated name that collides with the obfuscated name of that class file.

That's as far as I've gotten.

I'm half tempted to just merge Minecrift-Vive and Forge code manually and release ViveForgeCraft, but I fear I'd run into a whole new world of issues trying to get that to build.

**Comment by Tyrindor** [comment]
Well either way, I am glad your attempting to get it resolved. Majority of the reason I bought my Vive was for Minecraft, I play it a ton, and I'd love to have your tweaks. However, I've been playing with mods for ages now so going back to vanilla just doesn't work. Completely different games really.

I really hope it gets fixed, and I think I speak for everyone in here - we greatly appreciate the effort. If I knew more about coding I'd be digging through it.

**Comment by Nibala** [comment]
Just a thought: Wouldn't it be easier to split the project into the working renderer and build additions in the form of a normal mod? The vive renderer itself seems to work with mods, maybe it would be easier to remove the teleportation feature and put up vive specific stuff like controler key bind, teleportation and movement in the form of a mod. 

The implementation of mods seems to be a very well documented and straight forward process with few obstacles. The way the vive plugin now meddles with data is more like the forge installer itself and possibly very tricky now and for the future.

**Comment by jrbudda** [comment]
It has to be that way, you can't implement a whole new control scheme and rendering method 'on top' of minecraft as a mod, you have to override the functionality of the base game. There's ways to use external files to hold most of the changed code which keeps line by line changes to the base to a minimum but fiddling with the base is still necessary like what forge does.

I just need to either sit down and learn how it does the obfuscation and fix the installer, or just merge this and forge into one codebase, which I've already sorta started on.

**Comment by antifreak** [comment]
I have a question about this whole forge thing.
I have forge installed and it loads properly when i start minecraft with your versions.
Also i have installed seven Mods like NEI and Dynamic Lights wich are working flawelessly.

The only mods i cant get to work are adding new items to the game, like Decocraft, Carpenters or Buildcraft. Is this the problem you are discussing or are you talking about forge in general?

**Comment by jrbudda** [comment]
Basically yes, what works or doesnt is going to depend on what code the actual mods try to access. Some of my minecraft code is changed from the original and there seems to be a an issue with the installer that is breaking some of Forge's additions to the base game as well.

**Comment by jrbudda** [comment]
test v10 please. start new individual issues.

**Comment by Tyrindor** [comment]
Got excited but nope. I click play and it does some stuff but the game never launches. Did a fresh install
- Installed 1.7.10, launched and closed
- Installed forge
- Installed ViveCraft

Same thing, no mods installed (just stock + forge on top)
