### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by sabaal** [jrbudda/minecrift#337]
Error: java.lang.NoClassDefFoundError: jopenvr/HmdMatrix34_t
my device works fine with the 1.12&1.14 version.
full report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 19-12-23 下午4:34
Description: Initializing game

java.lang.NoClassDefFoundError: jopenvr/HmdMatrix34_t
	at bao.initMinecrift(Minecraft.java:4789)
	at bao.ag(Minecraft.java:840)
	at bao.f(Minecraft.java:1353)
	at net.minecraft.client.main.Main.main(Main.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: jopenvr.HmdMatrix34_t
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: jopenvr/AlignedStructure
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 12 more
Caused by: java.lang.ClassNotFoundException: jopenvr.AlignedStructure
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/Structure
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Structure
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at bao.initMinecrift(Minecraft.java:4789)
	at bao.ag(Minecraft.java:840)

-- Initialization --
Details:
Stacktrace:
	at bao.f(Minecraft.java:1353)
	at net.minecraft.client.main.Main.main(Main.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2020062088 bytes (1926 MB) / 2113929216 bytes (2016 MB) up to 2113929216 bytes (2016 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: vivecraft-1.7.10-jrbudda-40r7
	LWJGL: 2.9.1
	OpenGL: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_D1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.6.0 NVIDIA 441.66
	OpenGlRenderer: GeForce RTX 2080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Techjar** [comment]
A library is missing. Upload launcher_log.txt

**Comment by sabaal** [comment]
here is the log file
https://pastebin.com/DCFKCAcy

**Comment by Techjar** [comment]
Try manually downloading http://vivecraft.org/jar/com/sun/jna/4.2.1/jna-4.2.1.jar and putting it in `.minecraft/libraries/com/sun/jna/4.2.1`

**Comment by sabaal** [comment]
> Try manually downloading http://vivecraft.org/jar/com/sun/jna/4.2.1/jna-4.2.1.jar and putting it in `.minecraft/libraries/com/sun/jna/4.2.1`

it works!many thanks!

**Comment by Techjar** [comment]
Yeah this must be that stupid launcher bug that Mojang still hasn't fixed.
